name: Ontology Documentation CI

on: 
  push: 
      branches:
          - main
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python3-dev python3-pip -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2 rdflib shapely
         python3 docgeneration.py ttl/LimesDaicus_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes
         python3 docgeneration.py ttl/LimesGermaniaInferior_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes
         python3 docgeneration.py ttl/LimesNoricum_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes
         python3 docgeneration.py ttl/LimesPannoniaInferior_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes
         python3 docgeneration.py ttl/MidlandsWalesCornwall_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes         
         python3 docgeneration.py ttl/ObergermanischRaetischerLimes_result.ttl docs/ http://lod.squirrel.link/data/limes/ limes
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
